### ISSUE TITLE
Adding AngularJS template injection (sandbox bypasses)

### ISSUE THREAD

**Issue by sp1d3r** [EdOverflow/bugbounty-cheatsheet#2]
It would be nice to add AngularJS-related things from the end of the http://blog.portswigger.net/2016/01/xss-without-html-client-side-template.html article. I'm not sure, in which category we should put it (XSS, Template Injection, or make separate)

**Comment by EdOverflow** [comment]
What a coincidence! I was actually on planning on doing that next. :smiley:

**Comment by sp1d3r** [comment]
#3 PR filled

**Comment by M55-ai** [comment]
Wichser
