### ISSUE TITLE
We need to update this before [the Android change goes out](https://github.com/duckduckgo/Android/pull/3040) or we'll [screw up the activity screen](https://app.asana.com/0/0/1202824744465900/1204353323127524/f).

### ISSUE THREAD

**Issue by M55-ai** [EdOverflow/bugbounty-cheatsheet#88]
We need to update this before [the Android change goes out](https://github.com/duckduckgo/Android/pull/3040) or we'll [screw up the activity screen](https://app.asana.com/0/0/1202824744465900/1204353323127524/f).

_Originally posted by @laghee in https://github.com/duckduckgo/tracker-blocklists/pull/19_

**Comment by ItsIgnacioPortal** [comment]
stop spamming this repository
